import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

export default {
  darkMode: ['class'],
  content: ['./src/pages/**/*.{js,ts,jsx,tsx,mdx}', './src/components/**/*.{js,ts,jsx,tsx,mdx}', './src/app/**/*.{js,ts,jsx,tsx,mdx}'],
  safelist: [
    {
      pattern: /(border-.*-border|shadow-.*-normal)$/,
      variants: ['primary', 'secondary', 'accent', 'destructive'],
    },
    'hover:shadow-primary-hover',
    'hover:shadow-secondary-hover',
    'hover:shadow-accent-hover',
    'hover:shadow-destructive-hover',
  ],
  theme: {
    fontSize: {
      xs: ['1.2rem', { lineHeight: '1.6rem' }],
      sm: ['1.4rem', { lineHeight: '2rem' }],
      base: ['1.6rem', { lineHeight: '2.4rem' }],
      lg: ['1.8rem', { lineHeight: '2.8rem' }],
      xl: ['2rem', { lineHeight: '3rem' }],
      '2xl': ['2.4rem', { lineHeight: '3.2rem' }],
      '3xl': ['3rem', { lineHeight: '3.6rem' }],
      '4xl': ['3.6rem', { lineHeight: '4rem' }],
      '5xl': ['4.8rem', { lineHeight: '1' }],
      '6xl': ['6rem', { lineHeight: '1' }],
      '7xl': ['7.2rem', { lineHeight: '1' }],
      '8xl': ['9.6rem', { lineHeight: '1' }],
      '9xl': ['12.8rem', { lineHeight: '1' }],
    },
    spacing: {
      0: '0',
      1: '0.1rem',
      2: '0.2rem',
      4: '0.4rem',
      8: '0.8rem',
      12: '1.2rem',
      16: '1.6rem',
      20: '2rem',
      24: '2.4rem',
      28: '2.8rem',
      32: '3.2rem',
      36: '3.6rem',
      40: '4rem',
      44: '4.4rem',
      48: '4.8rem',
      52: '5.2rem',
      56: '5.6rem',
      60: '6rem',
      64: '6.4rem',
      72: '7.2rem',
      80: '8rem',
      96: '9.6rem',
    },
    extend: {
      screens: {
        sm: '576px',
        lg: '992px',
        xxl: '1300px',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          border: 'hsl(var(--primary-border))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          border: 'hsl(var(--secondary-border))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          border: 'hsl(var(--accent-border))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
          border: 'hsl(var(--destructive-border))',
        },
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        none: '0',
        sm: '0.2rem',
        DEFAULT: '0.4rem',
        md: '0.6rem',
        lg: '0.8rem',
        xl: '1.2rem',
        '2xl': '1.6rem',
        '3xl': '2.4rem',
        full: '100%',
      },
      boxShadow: {
        'primary-normal': 'hsl(var(--primary-border)) 0px 4px 0px',
        'primary-hover': 'hsl(var(--primary-border)) 0px 8px 0px',
        'secondary-normal': 'hsl(var(--secondary-border)) 0px 4px 0px',
        'secondary-hover': 'hsl(var(--secondary-border)) 0px 8px 0px',
        'destructive-normal': 'hsl(var(--destructive-border)) 0px 4px' + ' 0px',
        'destructive-hover': 'hsl(var(--destructive-border)) 0px 8px' + ' 0px',
        'accent-normal': 'hsl(var(--accent-border))' + ' 0px 4px' + ' 0px',
        'accent-hover': 'hsl(var(--accent-border))' + ' 0px 8px' + ' 0px',
      },
    },
  },
  plugins: [animate],
} satisfies Config;
